"""
ClaudeSkill: Anthropic Agent Skills compatibility for chak.

Supports loading Claude Agent Skills (SKILL.md format) and exposing them
as tools via function calling with three-layer progressive disclosure:

  Layer 1: name + description always visible to LLM as a function call tool
  Layer 2: full SKILL.md body returned when the skill is activated
  Layer 3: supporting files readable on demand via ClaudeSkillFileReader
"""

import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from .runner import ScriptRunner

# Binary file extensions excluded from file listings and content reading
_BINARY_EXTENSIONS = frozenset({
    '.ttf', '.otf', '.woff', '.woff2',
    '.png', '.jpg', '.jpeg', '.gif', '.bmp', '.ico', '.webp', '.svg',
    '.pdf', '.bin', '.exe', '.dll', '.so', '.dylib',
    '.zip', '.tar', '.gz', '.bz2', '.7z', '.rar',
    '.mp3', '.mp4', '.wav', '.avi', '.mov',
    '.db', '.sqlite',
    '.pyc', '.pyo',
})


def _parse_skill_md(path: Path):
    """Parse a SKILL.md file, extracting frontmatter fields and body.

    Args:
        path: Path to SKILL.md

    Returns:
        tuple: (name, description, body_text)

    Raises:
        FileNotFoundError: If path does not exist
        ValueError: If frontmatter is missing or lacks required fields
    """
    if not path.exists():
        raise FileNotFoundError(f"SKILL.md not found: {path}")

    content = path.read_text(encoding='utf-8')

    if not content.startswith('---'):
        raise ValueError(
            f"SKILL.md must begin with YAML frontmatter (---): {path}"
        )

    # Find the closing --- delimiter
    close = content.find('\n---', 3)
    if close == -1:
        raise ValueError(f"Unclosed frontmatter in SKILL.md: {path}")

    frontmatter_text = content[3:close]
    body = content[close + 4:].lstrip('\n')

    # Simple key: value parser (handles quoted and unquoted single-line values)
    fields: Dict[str, str] = {}
    for line in frontmatter_text.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or ':' not in line:
            continue
        key, _, raw_value = line.partition(':')
        key = key.strip()
        value = raw_value.strip()
        # Strip surrounding quotes (single or double)
        if len(value) >= 2 and value[0] in ('"', "'") and value[-1] == value[0]:
            value = value[1:-1]
        fields[key] = value

    name = fields.get('name', '').strip()
    description = fields.get('description', '').strip()

    if not name:
        raise ValueError(
            f"SKILL.md missing required 'name' field: {path}"
        )
    if not description:
        raise ValueError(
            f"SKILL.md missing required 'description' field: {path}"
        )

    return name, description, body


class ClaudeSkillFileReader:
    """Companion tool for ClaudeSkill that provides on-demand file reading (Layer 3).

    Allows the LLM to read specific files from the skill directory when needed,
    such as scripts, reference docs, or templates referenced in SKILL.md.

    This tool is auto-generated by ClaudeSkill and registered internally by
    ToolManager. Developers do not need to create or reference it directly.
    """

    def __init__(self, skill_name: str, skill_dir: Path):
        self._skill_name = skill_name
        self._skill_dir = skill_dir.resolve()

    @property
    def name(self) -> str:
        """Tool name: {skill_name}__read_file (e.g. pdf__read_file)."""
        return f"{self._skill_name}__read_file"

    @property
    def description(self) -> str:
        return (
            f"Read a file from the '{self._skill_name}' skill directory. "
            "Use this to access scripts, reference docs, or templates listed "
            "in the skill's available files."
        )

    def to_openai_tool(self) -> Dict[str, Any]:
        """Convert to OpenAI function calling format."""
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "path": {
                            "type": "string",
                            "description": (
                                f"Relative path to the file within the "
                                f"'{self._skill_name}' skill directory. "
                                "Example: 'scripts/extract.py' or 'reference.md'."
                            )
                        }
                    },
                    "required": ["path"]
                }
            }
        }

    async def call(self, arguments: Dict[str, Any], **kwargs) -> str:
        """Read a file from the skill directory.

        Args:
            arguments: Must contain 'path' key with a relative file path.

        Returns:
            File contents as a string, or an error/notice message.
        """
        rel_path = arguments.get('path', '').strip()
        if not rel_path:
            return "Error: 'path' argument is required."

        # Security: prevent path traversal outside the skill directory
        try:
            target = (self._skill_dir / rel_path).resolve()
        except Exception as e:
            return f"Error: Invalid path '{rel_path}': {e}"

        try:
            target.relative_to(self._skill_dir)
        except ValueError:
            return (
                "Error: Path traversal not allowed. "
                "The path must be within the skill directory."
            )

        if not target.exists():
            return f"Error: File not found: {rel_path}"

        if not target.is_file():
            return f"Error: '{rel_path}' is not a file."

        if target.suffix.lower() in _BINARY_EXTENSIONS:
            return (
                f"Cannot read binary file: {rel_path}\n"
                f"This file is a binary resource ({target.suffix}). "
                "Only text files can be read."
            )

        try:
            return target.read_text(encoding='utf-8')
        except UnicodeDecodeError:
            return (
                f"Cannot read file: {rel_path}\n"
                "File appears to be binary (could not decode as UTF-8)."
            )
        except Exception as e:
            return f"Error reading file '{rel_path}': {e}"

    def __repr__(self) -> str:
        return f"ClaudeSkillFileReader(skill='{self._skill_name}')"


class ClaudeSkill:
    """Load and expose an Anthropic Agent Skill (SKILL.md format) as a chak tool.

    Implements three-layer progressive disclosure per the Agent Skills specification:
    - Layer 1: name + description exposed to LLM via function calling
    - Layer 2: full SKILL.md body returned when the skill is activated
    - Layer 3: supporting files readable on demand via ClaudeSkillFileReader

    Example:
        from chak import Conversation
        from chak.tools.skills import ClaudeSkill

        skill = ClaudeSkill("./skills/pdf")

        conv = Conversation(
            model_uri="openai/gpt-4o",
            api_key="...",
            tools=[skill]
        )

        # Multiple skills
        skills = [ClaudeSkill(p) for p in ["./skills/pdf", "./skills/docx"]]
        conv = Conversation(..., tools=skills)
    """

    def __init__(self, skill_dir: str, runner: Optional[ScriptRunner] = None):
        """Load a Claude Agent Skill from a directory.

        Args:
            skill_dir: Path to the skill directory containing SKILL.md.
            runner: Optional skill-scoped script runner. When provided, the
                runner is exposed as an additional companion tool bound to this
                skill directory.

        Raises:
            FileNotFoundError: If skill_dir or SKILL.md does not exist.
            ValueError: If SKILL.md frontmatter is invalid or missing required fields.
        """
        self._skill_dir = Path(skill_dir).resolve()

        if not self._skill_dir.exists():
            raise FileNotFoundError(f"Skill directory not found: {skill_dir}")
        if not self._skill_dir.is_dir():
            raise FileNotFoundError(f"Not a directory: {skill_dir}")

        skill_md_path = self._skill_dir / 'SKILL.md'
        self._name, self._description, self._body = _parse_skill_md(skill_md_path)

        # Scan supporting files once at load time
        self._files = self._scan_files()

        # Cache companion tools
        self._file_reader = ClaudeSkillFileReader(self._name, self._skill_dir)
        self._runner = runner.bind(self._name, self._skill_dir) if runner else None

    @property
    def name(self) -> str:
        """Skill name from SKILL.md frontmatter."""
        return self._name

    @property
    def description(self) -> str:
        """Skill description from SKILL.md frontmatter."""
        return self._description

    def to_openai_tool(self) -> Dict[str, Any]:
        """Convert to OpenAI function calling format (Layer 1).

        Returns:
            OpenAI tool definition exposing name, description, and an optional
            instruction parameter.
        """
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "instruction": {
                            "type": "string",
                            "description": (
                                "Your goal or the user's request for this skill."
                            )
                        }
                    },
                    "required": []
                }
            }
        }

    async def call(self, arguments: Dict[str, Any], **kwargs) -> str:
        """Activate the skill and return its content (Layer 2).

        Returns the full SKILL.md body plus a manifest of available supporting
        files. The LLM should read this content and follow the skill's
        instructions. Supporting files are accessible via the companion
        read_file tool listed in the manifest.

        Args:
            arguments: May contain optional 'instruction' key.

        Returns:
            Formatted string with skill content and file manifest.
        """
        parts = [f"[Skill activated: {self.name}]", "", self._body]

        if self._files:
            reader_tool_name = self._file_reader.name
            parts.append("")
            parts.append("---")
            parts.append(
                f"Skill directory (absolute): {self._skill_dir}"
            )
            if self._runner is None:
                # Legacy hint preserved verbatim for callers that still pair
                # ClaudeSkill with a global Bash/Python tool (no runner
                # configured). Removing this would silently change prompt
                # behavior for existing single-skill setups.
                parts.append(
                    f"Available files (use {reader_tool_name} to read content, "
                    f"or use bash with 'python <skill_dir>/<path>' to execute scripts):"
                )
            else:
                parts.append(
                    f"Available files (use {reader_tool_name} to read content):"
                )
            for f in self._files:
                parts.append(f"- {f}")

        if self._runner is not None:
            runner_name = self._runner.name
            parts.append("")
            parts.append("Execution:")
            parts.append(
                f"Use {runner_name} to execute Python scripts in this skill. "
                "The runner executes with cwd fixed to this skill directory."
            )
            parts.append("Example arguments:")
            parts.append('{"script_path": "scripts/example.py", "stdin": "..."}')

        return "\n".join(parts)

    def get_file_reader(self) -> ClaudeSkillFileReader:
        """Return the companion file reader tool for this skill.

        The file reader is auto-registered by ToolManager, allowing the LLM
        to read supporting files from the skill directory on demand (Layer 3).
        Developers do not need to call this directly.
        """
        return self._file_reader

    def get_companion_tools(self) -> List[Any]:
        """Return all companion tools that should be registered with this skill."""
        tools: List[Any] = [self._file_reader]
        if self._runner is not None:
            tools.append(self._runner)
        return tools

    def _scan_files(self) -> List[str]:
        """Scan the skill directory for readable (non-binary) supporting files.

        Returns:
            Sorted list of relative file paths (excluding SKILL.md itself).
        """
        files = []

        for entry in sorted(self._skill_dir.rglob('*')):
            if not entry.is_file():
                continue
            # Skip SKILL.md at the skill root
            if entry.name == 'SKILL.md' and entry.parent == self._skill_dir:
                continue
            if entry.suffix.lower() in _BINARY_EXTENSIONS:
                continue
            rel = entry.relative_to(self._skill_dir)
            files.append(str(rel).replace(os.sep, '/'))

        return files

    def __repr__(self) -> str:
        return (
            f"ClaudeSkill(name='{self.name}', "
            f"files={len(self._files)}, "
            f"runner={self._runner is not None}, "
            f"dir='{self._skill_dir}')"
        )

    def __str__(self) -> str:
        return f"{self.name} (Claude Agent Skill)"
